In [1]:
import numpy as np

In [19]:
data = np.load('munged.npy.npz')

In [22]:
for key in data.keys():
    print(key)                        # x
    print(data[key]) 

output_rfl
[[0.15604483 0.14729504 0.13675882 ... 0.00625211 0.00280186 0.00076063]
 [0.16380462 0.15465124 0.14304265 ... 0.00520157 0.00171606 0.00091974]
 [0.16272633 0.15375729 0.14243665 ... 0.00478358 0.00148331 0.00095383]
 ...
 [0.1730771  0.16296801 0.15344223 ... 0.08317467 0.03568128 0.02234171]
 [0.16971041 0.15838021 0.14950973 ... 0.07854392 0.03286929 0.02226168]
 [0.17089832 0.15950367 0.15127327 ... 0.08271692 0.03492089 0.02047596]]
output_wv
[1.3337307  1.33441377 1.33562875 ... 0.40169749 0.40694392 0.40985647]
output_idx
[0 0 0 ... 7 7 7]


In [26]:
refls = data['output_rfl']
wv = data['output_wv']
fids = data['output_idx']

In [27]:
fids.shape

(9936,)